# Generated by Django 3.1.4 on 2021-01-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Título')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('experience', models.CharField(blank=True, max_length=5, verbose_name='Experiência')),
                ('img', models.ImageField(blank=True, null=True, upload_to='skills/image', verbose_name='Imagem')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['created_at'],
            },
        ),
    ]
